apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    uses: ' data intensive applications, data processing, machine learning, artificial
      intelligence'
  name: openshift-storage.ceph.rook.io
  selfLink: /apis/storage.k8s.io/v1/storageclasses/openshift-storage.ceph.rook.io
parameters:
  bucketclass: ceph-default-bucket-class
provisioner: ceph.rook.io/bucket
parameters:
  objectStoreNamespace: openshift-storage
  objectStoreName: ocs-storagecluster-cephobjectstore
reclaimPolicy: Retain
