apiVersion: starburstdata.com/v1
kind: Presto
metadata:
  name: presto-ocs
  namespace: presto
spec:
  nameOverride: presto-ocs
  licenseSecretName: presto-license
  image:
    name: registry.connect.redhat.com/starburst/presto:338-e.0-k8s-0.32-ubi8
    pullPolicy: IfNotPresent
  prometheus:
    enabled: true
    additionalRules:
      - pattern: 'presto.execution<name=TaskManager><>FailedTasks.TotalCount'
        name: 'failed_tasks'
        type: COUNTER
  service:
    type: ClusterIP
    name: presto-service
  memory:
    nodeMemoryHeadroom: 1Gi
  coordinator:
    cpuRequest: ""
    cpuLimit: "7"
    memoryAllocation: ""
  worker:
    count: 3
    prestoWorkerShutdownGracePeriodSeconds: 1
    cpuRequest: ""
    cpuLimit: ""
    memoryAllocation: ""
  hive:
#    awsSecretName: prestodb
    additionalProperties: |
      connector.name=hive-hadoop2
      hive.s3.use-instance-credentials=false
      hive.s3.endpoint=http://rook-ceph-rgw-s3a.openshift-storage.svc.cluster.local
      hive.s3.aws-access-key=433UEF6TZYJ9QKIGQES0
      hive.s3.aws-secret-key=KPh7MB85qg6pmEECGAo9AkMnJeuBSttTE2l0qxP4
      hive.s3.signer-type=AWSS3V4SignerType
      hive.s3.path-style-access=true
      hive.s3.use-instance-credentials=false
      hive.s3.staging-directory=/tmp
      hive.s3.ssl.enabled=false
      hive.s3.sse.enabled=false
      hive.s3.max-connections=100
    internalMetastore:
      s3Endpoint: http://rook-ceph-rgw-s3a.openshift-storage.svc.cluster.local
      image:
        imagepullPolicy: IfNotPresent
      memory: 0.5G
      cpu: 0.5
      postgreSql:
        jdbcUrl: jdbc:postgresql://postgresql.presto.svc.cluster.local/redhat
        username: redhat
        password: redhat
  additionalCatalogs:
    tpcds: |
      connector.name=tpcds
    postgresql: |
      connector.name=postgresql
      connection-url=jdbc:postgresql://postgresql.presto.svc.cluster.local/redhat
      connection-user=redhat
      connection-password=redhat
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: presto-route
  namespace: presto
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: presto-service
    weight: 100
  wildcardPolicy: None
