apiVersion: v1
kind: Service
metadata:
  name: ocs-external-rgw-lb
spec:
 ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ocs-external-rgw-lb
subsets:
  - addresses:
    - ip: 192.168.7.50
    ports:
    - port: 8080
  - addresses:
    - ip: 192.168.7.50
    ports:
    - port: 8081
  - addresses:
    - ip: 192.168.7.51
    ports:
    - port: 8080
  - addresses:
    - ip: 192.168.7.51
    ports:
    - port: 8081
  - addresses:
    - ip: 192.168.7.52
    ports:
    - port: 8080
  - addresses:
    - ip: 192.168.7.52
    ports:
    - port: 8081
  - addresses:
    - ip: 192.168.7.53
    ports:
    - port: 8080
  - addresses:
    - ip: 192.168.7.53
    ports:
    - port: 8081
  - addresses:
    - ip: 192.168.7.54
    ports:
    - port: 8080
  - addresses:
    - ip: 192.168.7.54
    ports:
    - port: 8081
  - addresses:
    - ip: 192.168.7.55
    ports:
    - port: 8080
  - addresses:
    - ip: 192.168.7.55
    ports:
    - port: 8081 
